# frozen_string_literal: true

plugins:
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/**/*
    - .bundle/**/*
    - vendor/**/*

Naming/PredicateMethod:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Max: 200

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 100

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/SafeNavigation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/Documentation:
  Enabled: false
